### ISSUE TITLE
Some improvements we can make

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/github-bot#1]
While we're using the bot to see what hiccups it has / what features we want, here are some immediate next steps:

- [ ] integrate with slack for monitoring
- [ ] write tests!
- [ ] -> PR linked to issue -> issue comes off board
- [ ] use RedwoodJS's api side 
- [ ] type more things, probably via comments (autocomplete is a godsend here)
- [x] try converting more stuff to graphql to see if it makes a difference
  - [x] in particular, every github resource has a globally unique node_id. it feels like we should be able to cache milestones node_ids somehow so we don't have to go fetch it everytime

**Comment by thedavidprice** [comment]
Idea --> use Redwood API as a Probot backend. Might also be a way to start getting github organization-level metrics.

**Comment by jtoar** [comment]
@thedavidprice that actually sounds totally doable given Redwood's awesome webhook integrations

**Comment by thedavidprice** [comment]
And/or coordinate with the project David T. is using...

**Comment by jtoar** [comment]
This issue's no longer relevant after the refactor; moreover, many of these have been implemented as part of the refactor.
