### ISSUE TITLE
don't change merge milestone if version

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/github-bot#2]
possible to check for milestone starts with `v` condition before changing?

https://s.tape.sh/mPacl92l

**Comment by jtoar** [comment]
Can definitely do 👍

**Comment by jtoar** [comment]
Should be fixed now:
https://github.com/redwoodjs/github-bot/blob/628a0e39797ba6bf529e787979562f8fc57c1802/index.js#L50-L53
