### ISSUE TITLE
Merged PR milestone change might not be working

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/github-bot#3]
Bot didn't work on this PR:
https://github.com/redwoodjs/redwood/pull/2795

Doing it now manually.

**Comment by thedavidprice** [comment]
And this one... definitely seems broken:
https://github.com/redwoodjs/redwood/pull/2866

TBD: monitoring/alerts/notifications --> anything we can do to have visibility, possibly in Slack channel?

**Comment by jtoar** [comment]
Thanks for reporting this, I found the error! 

> TBD: monitoring/alerts/notifications --> anything we can do to have visibility, possibly in Slack channel?

For sure something we can do, I'll get a fix out then dig into this

**Comment by jtoar** [comment]
Should be closed by https://github.com/redwoodjs/github-bot/commit/58afd20571e60008719aa4aeebee3e32d5e2a3aa. I'll monitor to make sure that's actually the case
